### ISSUE TITLE
Make it asynchronous 

### ISSUE THREAD

**Issue by itsnotrin** [EpikHost/PteroManager#1]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

As of right now, the requests are all made in HTTP. Once the bot has been developed out and we have all the basic requests down with the correct endpoints and headers, I'd like to preferably move over to aiohttp or an equivalent library to make the bot asynchronous and not just be blocking code throughout. 

### Describe the solution you'd like.

As described above, once we have the basics down, move it over to aiohttp or any other alternative.

**Comment by Jerry-py** [comment]
See #3 for it
