### ISSUE TITLE
Error on clicking button in ephemeral mode

### ISSUE THREAD

**Issue by SinghalChinmay** [EpikHost/PteroManager#12]
### Current Behavior

Right now, when clicking any button in the ephemeral mode of the `deleteserver` command, raises an error.

This happens because the program tries to edit the ephemeral message, but as the message is only shown to the person using the bot currently, it fails to edit the message.

### Expected Behavior

Buttons should get disabled and further proceedings should take place.

### Steps to Reproduce

Running `/deleteserver` command with having the `hide` option set to `True`

### Bot Version

latest

### Error Logs

```bash
Ignoring exception in view <Confirm timeout=180.0 children=2> for item <Button style=<ButtonStyle.success: 3> url=None disabled=True label='Confirm' emoji=None row=None>:
Traceback (most recent call last):
  File "F:\Chinmay\PteroManager\venv\lib\site-packages\discord\ui\view.py", line 371, in _scheduled_task
    await item.callback(interaction)
  File "F:\Chinmay\PteroManager\cogs\staff.py", line 28, in confirm
    await interaction.message.edit(view=self)
  File "F:\Chinmay\PteroManager\venv\lib\site-packages\discord\message.py", line 1386, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, **payload)
  File "F:\Chinmay\PteroManager\venv\lib\site-packages\discord\http.py", line 353, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by itsnotrin** [comment]
Good catch, will fix when I'm home

**Comment by SinghalChinmay** [comment]
Yup, sure!

**Comment by SinghalChinmay** [comment]
I think there are two approaches to this problem:

1. Remove the option for ephemeral messages entirely.
2. Give people the option of sending ephemeral messages, but with the initial message being publicly viewable and the rest of the communication taking place through ephemeral messaging.

**Comment by SinghalChinmay** [comment]
Hmm, I guess we do have two more options:

1. As editing an ephemeral message is not possible, we won't be disabling the buttons after the interaction message but, as we can see [here](https://github.com/EpikHost/PteroManager/blob/main/cogs/staff.py#L28) that the button after getting pressed are disabled in the backend (Basically the view stops listening for interactions), just not reflected on the frontend. Therefore the message would still be ephemeral, also the user will not be able to click the buttons multiple times.

2. Or still have the initial message be publicly visible, but as soon as the user presses the button, the message will be deleted and proceedings will take place in ephemeral messages.

What do you suggest? Do you have any other approach?

**Comment by itsnotrin** [comment]
I think the first method would work best for our usecase
